FROM python:3 as builder
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM python:3-alpine
COPY --from=builder /root/.cache /root/.cache
COPY --from=builder requirements.txt .
RUN pip install -r requirements.txt && rm -rf /root/.cache